### ISSUE TITLE
töö_7 parandus

### ISSUE THREAD

**Issue by kuuba** [heidilees/tudeng14-kodutood#1]
Kõik muu töös on kena, aga hulki ei moodustata nurksulgude abil (nii moodustatakse liste). Hulga tegemiseks tuleb kasutada loogelisi sulge või set() funktsiooni. in ja not in operaatorid toimivad muidugi ka listil aga teiste operaatoritega tekib probleeme.

**Comment by heidilees** [comment]
Kas teen faili muudatused või võtan lihtsalt teadmiseks?

**Comment by kuuba** [comment]
Võiks ikka muudatused sisse viia ja githubi "pushida". Siis on vähemalt 2 commit-i ja saab ise vaadata, mida versioonihaldamine endast tegelikult kujutab.

P.S. Väga vahva, et issue-trackimine nii sujuvalt käima läks. Kiiduväärt lausa.

**Comment by heidilees** [comment]
Nüüd sai lisatud ka parandatud versioon, kus hulkade tegemiseks kasutasin loogelisi {} sulge.

**Comment by kuuba** [comment]
Tundub, et nüüd on korras. Jõudu järgmise tegemiseks!
