### ISSUE TITLE
Töö 8

### ISSUE THREAD

**Issue by kuuba** [heidilees/tudeng14-kodutood#2]
Vaatasin koodi ja nimetaks seda päris heaks alguseks - omajagu on muidugi veel parandamist:
os ja argv sys teegist on imporditud aga kuskil neid ei kasutata; funktsiooni ruutjuur() oleks mõttekas defineerida main() funktsioonist väljapool, vastasel juhul ei saa me teda kuigi mugavalt moodulina kasutada ja ka kogu lokaalse konteksti mõte kaob ära; docstringe ega kommentaare pole üldse kasutatud; "executable" (x) bit pole failil dragonfishis ära märgitud; lõppeks - mingi väike üksik print on faili lõppu ära eksinud.

**Comment by heidilees** [comment]
Võtsin arvesse teie märkusi ja lisasin kodutöö 8st uue versiooni.

**Comment by kuuba** [comment]
Tundub et ongi korras. Õnnitlen - see on esimene töö 8 mille kohta ma tabelisse ok saan panna.

**Comment by kuuba** [comment]
Näib kena - rida 22-l on miskipärast funktsiooni lihtsalt niisama välja
kutsutud - see on täiesti üleliigne.

Parimat,
Toomas
